name: marcacion_facial_ekuasoft_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  shaky_animated_listview: ^0.0.5
  flutter_staggered_grid_view: ^0.7.0
  image_cropper: ^7.0.4
  image_picker: ^1.1.2
  auto_size_text: ^3.0.0
  flutter_pdfview: ^1.3.2
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  simple_shadow: ^0.3.1
  flutter_bloc: ^8.1.5
  go_router: ^14.1.3
  dio: ^5.4.3+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  flutter_slidable: ^3.1.0
  blur: ^3.1.0
  stomp_dart_client: ^2.0.0
  intl: ^0.19.0
  flutter_windowmanager: ^0.2.0
  provider: ^6.0.3
  geocoding: ^2.0.5
  flutter_riverpod: ^1.0.3
  no_screenshot: ^0.0.1+6
  local_auth: ^2.2.0
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

assets:
    - assets/

flutter:
  uses-material-design: true
